
// This file has been generated by the GUI designer. Do not modify.
namespace Bugziller
{
	public partial class BugsViewWidget
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hboxHeader;
		private global::Gtk.ComboBox comboServers;
		private global::Gtk.Button buttonUpdate;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.Entry entryFilter;
		private global::Gtk.Button buttonFilter;
		private global::Gtk.Label countLabel;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.ScrolledWindow listScrolled;
		private global::Gtk.TreeView bugsList;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button buttonRefresh;
		private global::Gtk.Label bugTitle;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.VBox commentsBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Bugziller.BugsViewWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Bugziller.BugsViewWidget";
			// Container child Bugziller.BugsViewWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hboxHeader = new global::Gtk.HBox ();
			this.hboxHeader.Name = "hboxHeader";
			this.hboxHeader.Spacing = 6;
			// Container child hboxHeader.Gtk.Box+BoxChild
			this.comboServers = global::Gtk.ComboBox.NewText ();
			this.comboServers.Name = "comboServers";
			this.hboxHeader.Add (this.comboServers);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxHeader [this.comboServers]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hboxHeader.Gtk.Box+BoxChild
			this.buttonUpdate = new global::Gtk.Button ();
			this.buttonUpdate.CanFocus = true;
			this.buttonUpdate.Name = "buttonUpdate";
			this.buttonUpdate.UseUnderline = true;
			this.buttonUpdate.Relief = ((global::Gtk.ReliefStyle)(2));
			this.buttonUpdate.Label = global::Mono.Unix.Catalog.GetString ("Update");
			this.hboxHeader.Add (this.buttonUpdate);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxHeader [this.buttonUpdate]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxHeader.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hboxHeader.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxHeader [this.vseparator1]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxHeader.Gtk.Box+BoxChild
			this.entryFilter = new global::Gtk.Entry ();
			this.entryFilter.CanFocus = true;
			this.entryFilter.Name = "entryFilter";
			this.entryFilter.IsEditable = true;
			this.entryFilter.InvisibleChar = '●';
			this.hboxHeader.Add (this.entryFilter);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxHeader [this.entryFilter]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hboxHeader.Gtk.Box+BoxChild
			this.buttonFilter = new global::Gtk.Button ();
			this.buttonFilter.CanFocus = true;
			this.buttonFilter.Name = "buttonFilter";
			this.buttonFilter.UseUnderline = true;
			this.buttonFilter.Relief = ((global::Gtk.ReliefStyle)(2));
			this.buttonFilter.Label = global::Mono.Unix.Catalog.GetString ("Filter");
			this.hboxHeader.Add (this.buttonFilter);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxHeader [this.buttonFilter]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hboxHeader.Gtk.Box+BoxChild
			this.countLabel = new global::Gtk.Label ();
			this.countLabel.Name = "countLabel";
			this.countLabel.Xalign = 0F;
			this.countLabel.LabelProp = "label2";
			this.hboxHeader.Add (this.countLabel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxHeader [this.countLabel]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 7;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add (this.hboxHeader);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hboxHeader]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 570;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.listScrolled = new global::Gtk.ScrolledWindow ();
			this.listScrolled.Name = "listScrolled";
			this.listScrolled.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child listScrolled.Gtk.Container+ContainerChild
			this.bugsList = new global::Gtk.TreeView ();
			this.bugsList.CanFocus = true;
			this.bugsList.Name = "bugsList";
			this.bugsList.RulesHint = true;
			this.listScrolled.Add (this.bugsList);
			this.vpaned1.Add (this.listScrolled);
			global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.listScrolled]));
			w9.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonRefresh = new global::Gtk.Button ();
			this.buttonRefresh.CanFocus = true;
			this.buttonRefresh.Name = "buttonRefresh";
			this.buttonRefresh.UseUnderline = true;
			this.buttonRefresh.Label = global::Mono.Unix.Catalog.GetString ("Update from Server");
			this.hbox1.Add (this.buttonRefresh);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonRefresh]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.bugTitle = new global::Gtk.Label ();
			this.bugTitle.Name = "bugTitle";
			this.bugTitle.Xalign = 0F;
			this.bugTitle.Selectable = true;
			this.hbox1.Add (this.bugTitle);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.bugTitle]));
			w11.Position = 1;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w13 = new global::Gtk.Viewport ();
			w13.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.commentsBox = new global::Gtk.VBox ();
			this.commentsBox.Name = "commentsBox";
			this.commentsBox.Spacing = 8;
			w13.Add (this.commentsBox);
			this.GtkScrolledWindow1.Add (w13);
			this.vbox3.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow1]));
			w16.Position = 1;
			this.vpaned1.Add (this.vbox3);
			global::Gtk.Paned.PanedChild w17 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.vbox3]));
			w17.Resize = false;
			w17.Shrink = false;
			this.vbox2.Add (this.vpaned1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vpaned1]));
			w18.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.comboServers.Changed += new global::System.EventHandler (this.OnComboServersChanged);
			this.buttonUpdate.Clicked += new global::System.EventHandler (this.OnButtonUpdateClicked);
			this.entryFilter.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnEntryFilterKeyPressEvent);
			this.buttonFilter.Clicked += new global::System.EventHandler (this.OnButtonFilterClicked);
			this.bugsList.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnBugsListButtonPressEvent);
			this.bugsList.PopupMenu += new global::Gtk.PopupMenuHandler (this.OnBugsListPopupMenu);
			this.bugsList.RowActivated += new global::Gtk.RowActivatedHandler (this.OnBugsListRowActivated);
			this.buttonRefresh.Clicked += new global::System.EventHandler (this.OnButtonRefreshClicked);
		}
	}
}
